name: Sync Install Script to OSS

on:
  push:
    branches:
      - main
    paths:
      - 'all-in-one/get-ai-gateway.sh'
  workflow_dispatch: ~

jobs:
  sync-to-oss:
    runs-on: ubuntu-latest
    environment:
      name: oss
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync to OSS
        uses: go-choppy/ossutil-github-action@master
        with:
          ossArgs: 'cp all-in-one/get-ai-gateway.sh oss://higress-ai/ai-gateway/install.sh'
          accessKey: ${{ secrets.ACCESS_KEYID }}
          accessSecret: ${{ secrets.ACCESS_KEYSECRET }}
          endpoint: oss-cn-hongkong.aliyuncs.com
